# Generated by Django 4.0.3 on 2022-04-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuser',
            new_name='user',
        ),
    ]
