# Generated by Django 4.0.3 on 2022-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_rename_uuser_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
