# Generated by Django 4.0.3 on 2022-04-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
